/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FreightIntelligenceRouteImport } from './routes/freight-intelligence'
import { Route as IndexRouteImport } from './routes/index'

const FreightIntelligenceRoute = FreightIntelligenceRouteImport.update({
  id: '/freight-intelligence',
  path: '/freight-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/freight-intelligence': typeof FreightIntelligenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/freight-intelligence': typeof FreightIntelligenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/freight-intelligence': typeof FreightIntelligenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/freight-intelligence'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/freight-intelligence'
  id: '__root__' | '/' | '/freight-intelligence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FreightIntelligenceRoute: typeof FreightIntelligenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/freight-intelligence': {
      id: '/freight-intelligence'
      path: '/freight-intelligence'
      fullPath: '/freight-intelligence'
      preLoaderRoute: typeof FreightIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FreightIntelligenceRoute: FreightIntelligenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
